<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Fixtures\small-blind-state.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\JevBalatroBot.Core\JevBalatroBot.Core.csproj" />
    <ProjectReference Include="..\..\src\JevBalatroBot.Balatro\JevBalatroBot.Balatro.csproj" />
    <ProjectReference Include="..\..\src\JevBalatroBot.Jev\JevBalatroBot.Jev.csproj" />
    <ProjectReference Include="..\..\src\JevBalatroBot.Agent\JevBalatroBot.Agent.csproj" />
  </ItemGroup>

</Project>
